version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: careerpath-db-prod
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: CareerPathDb
    ports:
      - "5432:5432" # Standard Postgres port
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - ai_shared_network
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: careerpath-azurite-prod
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --skipApiVersionCheck"
    ports:
      - "10000:10000" 
    volumes:
      - azurite_data_prod:/data
    networks:
      - ai_shared_network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Host/Dockerfile
    container_name: careerpath-api-prod
    environment:
      # 1. Core .NET Settings
      - ASPNETCORE_ENVIRONMENT=Production
      
      # 2. Database Connection (Overrides appsettings)
      - ConnectionStrings__DefaultConnection=Host=careerpath-db-prod;Port=5432;Database=CareerPathDb;Username=${DB_USER:-postgres};Password=${DB_PASSWORD}
      
      # 3. Security & Super Admin
      - SuperAdmin__Email=${SUPERADMIN_EMAIL}
      - SuperAdmin__Password=${SUPERADMIN_PASSWORD}
      - JwtOptions__SecretKey=${JWT_SECRET_KEY}
      
      # 4. External Services (Routing over the shared network)
      - AiModelService__BaseUrl=http://fast_inference_api:8000/
      
      # 5. Email Settings (SMTP)
      - EmailSettings__Host=${SMTP_HOST}
      - EmailSettings__Port=${SMTP_PORT}
      - EmailSettings__Username=${SMTP_USERNAME}
      - EmailSettings__Password=${SMTP_PASSWORD}
     # 6. CORS Origin & ٍStorage URLs
      - Storage__IsLocalContainer=${PROD_STORAGE_IS_LOCAL}
      - Storage__CorsAllowedOrigin=${PROD_CORS_ORIGIN}
      - Storage__InternalStorageUrl=${PROD_INTERNAL_STORAGE_URL}
      - Storage__ExternalStorageUrl=${PROD_EXTERNAL_STORAGE_URL}
      - FrontendUrl=${PROD_FRONTEND_URL}

    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ai_shared_network
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: careerpath-caddy
    restart: unless-stopped
    ports:
      - "80:80"    # Standard HTTP port
      - "443:443"  # Secure HTTPS port
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ai_shared_network
    depends_on:
      - api
      - azurite
volumes:
  postgres_data_prod:
  azurite_data_prod:
  caddy_data:     # Saves your SSL certificates so they don't get lost
  caddy_config:   # Saves Caddy's internal configuration
networks:
  ai_shared_network:
    external: true
    name: ai_shared_network
