// <auto-generated />
using System;
using CareerPath.Assessment.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerPath.Assessment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AssessmentsDbContext))]
    [Migration("20260409122552_AddOutboxMessagesTable")]
    partial class AddOutboxMessagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assessments")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerPath.Assessment.Core.Entities.AssessmentResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrimaryConfidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("PrimaryJobLabel")
                        .HasColumnType("integer");

                    b.Property<decimal>("SecondaryConfidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("SecondaryJobLabel")
                        .HasColumnType("integer");

                    b.Property<decimal>("TertiaryConfidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("TertiaryJobLabel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentSubmissionId")
                        .IsUnique();

                    b.ToTable("AssessmentResults", "assessments");
                });

            modelBuilder.Entity("CareerPath.Assessment.Core.Entities.AssessmentSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RawAnswersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AssessmentSubmissions", "assessments");
                });

            modelBuilder.Entity("CareerPath.Assessment.Core.Entities.AssessmentResult", b =>
                {
                    b.HasOne("CareerPath.Assessment.Core.Entities.AssessmentSubmission", "Submission")
                        .WithOne("Result")
                        .HasForeignKey("CareerPath.Assessment.Core.Entities.AssessmentResult", "AssessmentSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("CareerPath.Assessment.Core.Entities.AssessmentSubmission", b =>
                {
                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
