using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using CareerPath.Profiles.Core.Entities;

namespace CareerPath.Profiles.Infrastructure.Persistence.Configurations
{
    public class UserProfileConfiguration : IEntityTypeConfiguration<UserProfile>
    {
        public void Configure(EntityTypeBuilder<UserProfile> builder)
        {
            builder.ToTable("UserProfiles", "profiles");

            // Primary Key: Passed from Identity integration event, not generated by this DB
            builder.HasKey(p => p.UserId);
            builder.Property(p => p.UserId).ValueGeneratedNever();

            builder.Property(p => p.DisplayName).IsRequired().HasMaxLength(100);
            builder.Property(p => p.Bio).HasMaxLength(500);
            builder.Property(p => p.AvatarUrl).HasMaxLength(500);

            // Stored as integer per your instruction
            builder.Property(p => p.Type).IsRequired();

            builder.Property(p => p.ReputationScore).IsRequired().HasDefaultValue(0);
            builder.Property(p => p.IsAcceptingDirectMessages).IsRequired().HasDefaultValue(false);

            // Soft links to other modules (No Foreign Key constraints)
            builder.Property(p => p.PrimarySectorId).IsRequired();
            builder.Property(p => p.TargetCareerId);
            builder.Property(p => p.LatestAssessmentId);

            // Audit fields
            builder.Property(p => p.CreatedAt).IsRequired();
            builder.Property(p => p.UpdatedAt);
        }
    }
}